name = "qr-generator"
main = "app/.output/server/index.mjs"
compatibility_date = "2025-06-04"
compatibility_flags = ["nodejs_compat"]

# Deployment settings
minify = true
send_metrics = false

[assets]
directory = "app/.output/public"

# D1 Database configuration
[[d1_databases]]
binding = "DB"
database_name = "qr-generator-db"
database_id = "a57c8299-54e0-43f3-889d-3c09539dcf0b"

# R2 Storage configuration  
[[r2_buckets]]
binding = "QR_IMAGES"
bucket_name = "qr-generator-qrs"

# Environment variables
[vars]
BASE_URL = "https://qr.matg.dev"
NODE_ENV = "production"

# Production environment overrides
[env.production]
name = "qr-generator"

[env.production.vars]
BASE_URL = "https://qr.matg.dev"
NODE_ENV = "production"

# Development/staging can override if needed
[env.staging]
name = "qr-generator-staging"

[env.staging.vars]
BASE_URL = "https://staging.qr.matg.dev"
NODE_ENV = "staging"

# Observability and logging
[observability.logs]
enabled = true

# Worker limits and performance
[limits]
cpu_ms = 50

# For SSR/streaming support
usage_model = "standard"
