name = "qr-generator"
main = "app/.output/server/index.mjs"
compatibility_date = "2025-06-04"
compatibility_flags = ["nodejs_compat"]

# Deployment settings
minify = true
send_metrics = false

[assets]
directory = "app/.output/public"

# D1 Database configuration
[[d1_databases]]
binding = "DB"
database_name = "qr-generator-db"
database_id = "${D1_DATABASE_ID}"

# R2 Storage configuration
[[r2_buckets]]
binding = "QR_IMAGES"
bucket_name = "${R2_BUCKET_NAME}"

# Environment variables
[vars]
BASE_URL = "${BASE_URL}"
NODE_ENV = "production"

# Observability and logging
[observability.logs]
enabled = true

# Worker limits and performance
[limits]
cpu_ms = 50

# For SSR/streaming support
usage_model = "standard"
