name = "qr-generator"
main = "app/.output/server/index.mjs"
compatibility_date = "2025-06-21"

[assets]
directory = "app/.output/public"

# D1 Database configuration
[[d1_databases]]
binding = "DB"
database_name = "qr-generator-db"
database_id = "a57c8299-54e0-43f3-889d-3c09539dcf0b"

# R2 Storage configuration
[[r2_buckets]]
binding = "QR_IMAGES"
bucket_name = "qr-generator-qrs"

#[vars]
#MY_ENV_VAR = "value"

# Optional: Set usage model to 'unbound' for SSR/streaming
#usage_model = "unbound"
